package edu.duke.bookpublishing.sales.dto;

import edu.duke.bookpublishing.sales.BookFinancialSummary;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import lombok.Builder;

/**
 * DTO for the Book Financial Response. This class returns the requested aggregates for a book's
 * (publisher) revenue, unpaid author royalty, paid author royalty, and total author royalty.
 * (Evolution 1, Req 2.2.2)
 *
 * @author Daniel Rodriguez-Florido
 */
@Builder
@Schema(
    description =
        "Book Financials response data (publisher revenue, unpaid author royalty, paid author royalty, total author royalty)")
public record BookFinancialSummaryResponse(
    @Schema(description = "The id of the book that the financials correspond to") Long bookId,
    @Schema(description = "The publisher revenue generated by this book") BigDecimal revenue,
    @Schema(description = "The unpaid author royalty for this book") BigDecimal unpaidRoyalty,
    @Schema(description = "The paid author royalty for this book") BigDecimal paidRoyalty,
    @Schema(description = "The total author royalty earned for this book")
        BigDecimal totalRoyalty) {

  public static BookFinancialSummaryResponse from(BookFinancialSummary bookFinancialSummary) {
    return new BookFinancialSummaryResponse(
        bookFinancialSummary.bookId(),
        bookFinancialSummary.revenue(),
        bookFinancialSummary.unpaidRoyalty(),
        bookFinancialSummary.paidRoyalty(),
        bookFinancialSummary.totalRoyalty());
  }
}
