# Common settings
spring.application.name=book-publishing

# Default to dev profile
spring.profiles.active=dev

# OpenAPI / Swagger configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=edu.duke.bookpublishing
springdoc.paths-to-match=/api/**